/* Shared resources: scene metadata, UI strings and idle prompt tables. */
#include "ai_app_data.h"

SceneInfo g_scenes[MAX_SCENE_COUNT] =
{
    {TXT_SCENE_SHOPPING, TXT_SCENE_SHOPPING_INTRO, "shopping", AVATAR_HAPPY},
    {TXT_SCENE_GAMING, TXT_SCENE_GAMING_INTRO, "gaming", AVATAR_CURIOUS},
    {TXT_SCENE_CAFE, TXT_SCENE_CAFE_INTRO, "cafe", AVATAR_GENTLE},
    {TXT_SCENE_LIBRARY, TXT_SCENE_LIBRARY_INTRO, "library", AVATAR_GENTLE},
    {TXT_SCENE_NIGHT, TXT_SCENE_NIGHT_INTRO, "night", AVATAR_SHY},
    {TXT_SCENE_ENCOURAGE, TXT_SCENE_ENCOURAGE_INTRO, "encourage", AVATAR_HAPPY},
    {TXT_SCENE_WALK, TXT_SCENE_WALK_INTRO, "walk", AVATAR_CURIOUS},
    {TXT_SCENE_DINNER, TXT_SCENE_DINNER_INTRO, "dinner", AVATAR_HAPPY},
    {TXT_SCENE_MOVIE, TXT_SCENE_MOVIE_INTRO, "movie", AVATAR_CURIOUS},
    {TXT_SCENE_MUSIC, TXT_SCENE_MUSIC_INTRO, "music", AVATAR_GENTLE},
    {TXT_SCENE_EXAM, TXT_SCENE_EXAM_INTRO, "exam", AVATAR_GENTLE},
    {TXT_SCENE_REST, TXT_SCENE_REST_INTRO, "rest", AVATAR_SHY}
};

const uint8_t g_scene_count = MAX_SCENE_COUNT;

IdleFeedback g_idle_feedbacks[4] =
{
    {TXT_IDLE_1, AVATAR_GENTLE},
    {TXT_IDLE_2, AVATAR_HAPPY},
    {TXT_IDLE_3, AVATAR_SHY},
    {TXT_IDLE_4, AVATAR_CURIOUS}
};

const uint8_t g_idle_feedback_count = 4;
